# i/o parameters

# Where are the final results published?
output_dir: "vlight_out"

# How are the final results published?
# By default, files are copied from the work-dir.
# Valid settings: "copy", "move", "link", "symlink"
# ATT: "link" does not work on all filesystems, such as some /scratch volumes
publish_mode: "copy"

# path to mailx/mail application for email notifications -- EXPERIMENTAL
mailer: "/usr/bin/mail"

# email address for receiving email notifications -- EXPERIMENTAL
email: false


# workflow parameters

# run preprocessing/qc workflow
# alternative parameter: skip_preprocessing
run_preprocessing: true


# qc parameters
# (also refer to: https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/bbduk-guide/)

# minimum read length [bp]
# NGLess functional profiling: 45
# 16S GAGA2: 100
qc_minlen: 45

# bbduk wgs
# qtrim=rl trimq=3 : gentle quality trimming (only discard bases < phred 3; phred 2 = junk marker) on either side (rl) of the read
# maq=25 : discard reads below average quality of pred 25
# ref=?? ktrim=r k=23 mink=11 hdist=1 tpe tbo : right-side k-mer based adapter clipping with 1 mismatch allowed, try overlap-detection (tbo), and trim pairs to same length (tpe) upon adapter detection -- NOTE: ref-parameter is set within workflow
# ftm=5 : get rid of (n*5)+1st base (last sequencing cycle illumina garbage) -- NOTE: unset for preprocessed data
# entropy=0.5 entropywindow=50 entropyk=5 : discard low complexity sequences
qc_params_shotgun: "qtrim=rl trimq=3 maq=25 ktrim=r k=23 mink=11 hdist=1 ftm=5 entropy=0.5 entropywindow=50 entropyk=5 tpe tbo"


# kraken2 parameters

# kraken2 db path
kraken_database: "/g/scb/zeller/jawirbel/total_RNAseq/databases/kraken2_standard"

# kraken2_min_hit_groups
kraken2_min_hit_groups: 10


# pathseq parameters

# path to pathseq db (currently not supported)
# pathseq_database: "/g/scb/zeller/fspringe/Database/PathSeq_Legacy"

# paths to pathseq db files
pathseq_database: "/g/scb/zeller/fspringe/Database/PathSeq_Dohlman"
pathseq_db_filter_bwa_image: "/g/scb/zeller/fspringe/Database/PathSeq_Dohlman/pathseq_host.fa.img"
pathseq_db_kmer_file: "/g/scb/zeller/fspringe/Database/PathSeq_Dohlman/pathseq_host.bfi"
pathseq_db_microbe_fasta: "/g/scb/zeller/fspringe/Database/PathSeq_Dohlman/pathseq_microbe.fa"
pathseq_db_microbe_bwa_image: "/g/scb/zeller/fspringe/Database/PathSeq_Dohlman/pathseq_microbe.fa.img"
pathseq_db_taxonomy_file: "/g/scb/zeller/fspringe/Database/PathSeq_Dohlman/pathseq_taxonomy.db"

# minimum readlength for pathseq to consider
pathseq_min_clipped_read_length: 31


# collate parameters
GTDB_markers: "/g/scb/zeller/fspringe/Database/GTDB/GTDB_marker_gene_lengths.tsv"
